apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_HOST: Y291cnNleS1kYXRhYmFzZS1zZXJ2aWNl
  MYSQL_ROOT_PASSWORD: Z3J5ZmZpbjA4MTE=
  MYSQL_USER: Z3J5ZmZpbjA4MTE=
  MYSQL_DATABASE: ZG9ja2VyLXBocA==
  MYSQL_PASSWORD: Z3J5ZmZpbjA4MTE=
  PMA_HOST: ZGI=
  HOST_NAME: Z3J5ZmZpbi11aXQuc2l0ZQ==
  MAIL_USERNAME: a2hvYXRuQHRlbnNvcmFjdC5pbw==
  PASS_APP: dW9ibyBlaWFtIGlqbWkgY2x6eQ==