apiVersion: v1
kind: Service
metadata:
  name: coursey-database-service
  labels:
    app: coursey-database
spec:
  selector:
    app: coursey-database
  ports:
  - port: {{ .Values.mysql.service.port }}      
    targetPort: mysql-port
    protocol: TCP
  type: ClusterIP