apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    app: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }} 
  storageClassName: {{ .Values.mysql.persistence.storageClass }} 