apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: coursey-php
spec:
  selector:
    app: coursey-php  
  ports:
  - port: {{ .Values.php.service.port }}       
    targetPort: {{ .Values.php.service.port }}  
    protocol: TCP
    name: php-fpm
  type: ClusterIP    